#**************************************************************#
#**************************************************************#
#**************		Author: Adham Hossam		***************# 
#**************			 MakeFile				***************#
#**************************************************************#
#**************************************************************#
#**************************************************************#


# ToolChain
CC =arm-none-eabi-

CFLAGS = -mthumb -mcpu=cortex-m3 -gdwarf-2

LIBS = 

# Include
INCS = -I .

# Source files and object files
SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)

# Assemble files and object files
As = $(wildcard *.s)
As_OBJ = $(As:.s=.o)

# Project Name
Project_Name = Project_CortexM3


all: $(Project_Name).bin
	@echo "=========== Build is Done ==========="
	
#startup.o: startup.s
%.s: %.o
	$(CC)as.exe $(CFLAGS) $< -o $@
	
%.o: %.c
	$(CC)gcc.exe -c $(INCS) $(CFLAGS) $< -o $@
	


$(Project_Name).elf: $(OBJ) $(As_OBJ)
	$(CC)ld.exe -T linker_script.ld $(LIBS) $(OBJ) $(As_OBJ) -o $@ -Map=Map_File.map

$(Project_Name).bin: $(Project_Name).elf
	$(CC)objcopy.exe -O binary $< $@
	
clean_all:
	rm *.o *.bin *.elf
	
clean:
	rm *.elf *.bin
	