#**************************************************************#
#**************************************************************#
#**************		Author: Adham Hossam		***************# 
#**************			 MakeFile				***************#
#**************************************************************#
#**************************************************************#
#**************************************************************#

# ToolChain
CC =arm-none-eabi-

#-gdwarf-2
CFLAGS = -mthumb -mcpu=cortex-m3 

LIBS = 

# Include
INCS = -I . -Iinc

# Source files and object files
SRC = $(wildcard *.c) $(wildcard src/*.c) 
OBJ = $(SRC:.c=.o)

# Assemble files and object files
As = $(wildcard *.s)
As_OBJ = $(As:.s=.o)

# Project Name
Project_Name = HighPressureDetectionSystem


all: $(Project_Name).bin $(Project_Name).hex
	@echo "=========== Build is Done ==========="
	
#startup.o: startup.s
%.s: %.o
	$(CC)as.exe $(CFLAGS) $< -o $@
	
%.o: %.c
	$(CC)gcc.exe -c $(INCS) $(CFLAGS) $< -o $@
	
$(Project_Name).bin: $(Project_Name).elf
	$(CC)objcopy.exe -O binary $< $@
	
$(Project_Name).hex: $(Project_Name).elf
	$(CC)objcopy.exe -O ihex $< $@
	
$(Project_Name).elf: $(OBJ) $(As_OBJ)
	$(CC)ld.exe -T linker_script.ld $(LIBS) $(OBJ) $(As_OBJ) -o $@ -Map=Map_File.map
	
clean_all:
	rm src/*.o *.o *.bin *.elf *.hex *.map
	
clean:
	rm *.elf *.bin
	