#**************************************************************#
#**************************************************************#
#**************		Author: Adham Hossam		***************# 
#**************			 MakeFile				***************#
#**************************************************************#
#**************************************************************#
#**************************************************************#


# ToolChain
CC =arm-none-eabi-

CFLAGS =-g -mcpu=arm926ej-s

LIBS = 

# Include
INCS = -I .

# Source files and object files
SRC = $(wildcard *.c)
OBJ = $(SRC:.c=.o)

# Assemble files and object files
As = $(wildcard *.s)
As_OBJ = $(As:.s=.o)

# Project Name
Project_Name = project


all: $(Project_Name).bin
	@echo "=========== Build is Done ==========="

startup.o: startup.s
	$(CC)as.exe $(CFLAGS) $< -o $@
	
%.o: %.c
	$(CC)gcc.exe -c $(INCS) $(CFLAGS) $< -o $@
	


$(Project_Name).elf: $(OBJ) $(As_OBJ)
	$(CC)ld.exe -T linker_script.ld $(LIBS) $(OBJ) $(As_OBJ) -o $@

$(Project_Name).bin: $(Project_Name).elf
	$(CC)objcopy.exe -O binary $< $@
	
clean_all:
	rm *.o *.bin *.elf
	
clean:
	rm *.elf *.bin
	